
export interface Make {
    value: string;
    viewValue: string;
  };

export const allMakes = [  
    {  
       "value":"Acura",
       "viewValue":"Acura"
    },
    {  
       "value":"Audi",
       "viewValue":"Audi"
    },
    {  
       "value":"BMW",
       "viewValue":"BMW"
    },
    {  
       "value":"Buick",
       "viewValue":"Buick"
    },
    {  
       "value":"Cadillac",
       "viewValue":"Cadillac"
    },
    {  
       "value":"Chevrolet",
       "viewValue":"Chevrolet"
    },
    {  
       "value":"Chrysler",
       "viewValue":"Chrysler"
    },
    {  
       "value":"Dodge",
       "viewValue":"Dodge"
    },
    {  
       "value":"Fiat",
       "viewValue":"Fiat"
    },
    {  
       "value":"Ford",
       "viewValue":"Ford"
    },
    {  
       "value":"GMC",
       "viewValue":"GMC"
    },
    {  
       "value":"Genesis",
       "viewValue":"Genesis"
    },
    {  
       "value":"Honda",
       "viewValue":"Honda"
    },
    {  
       "value":"Hummer",
       "viewValue":"Hummer"
    },
    {  
       "value":"Hyundai",
       "viewValue":"Hyundai"
    },
    {  
       "value":"Infiniti",
       "viewValue":"Infiniti"
    },
    {  
       "value":"Jaguar",
       "viewValue":"Jaguar"
    },
    {  
       "value":"Jeep",
       "viewValue":"Jeep"
    },
    {  
       "value":"Kia",
       "viewValue":"Kia"
    },
    {  
       "value":"Land Rover",
       "viewValue":"Land Rover"
    },
    {  
       "value":"Lexus",
       "viewValue":"Lexus"
    },
    {  
       "value":"Lincoln",
       "viewValue":"Lincoln"
    },
    {  
       "value":"Mazda",
       "viewValue":"Mazda"
    },
    {  
       "value":"Mercedes-Benz",
       "viewValue":"Mercedes-Benz"
    },
    {  
       "value":"Mercury",
       "viewValue":"Mercury"
    },
    {  
       "value":"Mini",
       "viewValue":"Mini"
    },
    {  
       "value":"Mitsubishi",
       "viewValue":"Mitsubishi"
    },
    {  
       "value":"Nissan",
       "viewValue":"Nissan"
    },
    {  
       "value":"Pontiac",
       "viewValue":"Pontiac"
    },
    {  
       "value":"Porsche",
       "viewValue":"Porsche"
    },
    {  
       "value":"Saturn",
       "viewValue":"Saturn"
    },
    {  
       "value":"Scion",
       "viewValue":"Scion"
    },
    {  
       "value":"Smart",
       "viewValue":"Smart"
    },
    {  
       "value":"Subaru",
       "viewValue":"Subaru"
    },
    {  
       "value":"Tesla",
       "viewValue":"Tesla"
    },
    {  
       "value":"Toyota",
       "viewValue":"Toyota"
    },
    {  
       "value":"Volkswagen",
       "viewValue":"Volkswagen"
    },
    {  
       "value":"Volvo",
       "viewValue":"Volvo"
    }
 ];